Update waf to 1.9.3 to fix compilation with Python 3.4+
The current version of waf fails with the following error on Python 3.4:

_pickle.PicklingError: Can't pickle <class
'waflib.Node.Context.__init__.<locals>.node_class'>: attribute lookup
Context.__init__.<locals>.node_class on waflib.Node failed

Update to latest 1.9.3. Tested on Python 2.7.10 & 3.4.3.

Signed-off-by: Doug Nazar <nazard@nazar.ca>